on:
  push:
    branches: [ main ]

name: Deploy New Version App FastApi

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get Short GitHub SHA and Save in Environment Variable
      run: echo "SHORT_GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: latest
      run: |
        echo "Building Docker image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_GITHUB_SHA . 
        echo "Docker image built successfully."
    
        echo "Pushing Docker image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
        echo "Docker image pushed successfully."
    
  deploy_dev:
    name: deploy_dev
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}

    - name: Clone charts HELM
      run: |
        git clone https://github.com/Datascientest-DevOps-2024/helm-chart-db.git
        git clone https://github.com/Datascientest-DevOps-2024/helm-chart-fastapi.git
        
    - name: Get Short GitHub SHA and Save in Environment Variable
      run: echo "SHORT_GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Install Charts db and Fastapi - dev
      run: |
        sed -i "s+tag.*+tag: $SHORT_GITHUB_SHA+g" helm-chart-fastapi/values_dev.yaml
        cat helm-chart-fastapi/values_dev.yaml
        helm upgrade --install db ./helm-chart-db --values=helm-chart-db/values.yaml --namespace dev
        helm upgrade --install fastapi ./helm-chart-fastapi --values=helm-chart-fastapi/values_dev.yaml --namespace dev
  
  deploy_prod:
    name: deploy_prod
    needs: [deploy_dev]
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_DEFAULT_REGION }}

    - name: Clone charts HELM
      run: |
        git clone https://github.com/Datascientest-DevOps-2024/helm-chart-db.git
        git clone https://github.com/Datascientest-DevOps-2024/helm-chart-fastapi.git

    - name: Install Charts db and Fastapi - dev
      run: |
        helm upgrade --install db ./helm-chart-db --values=helm-chart-db/values.yaml --namespace dev
        helm upgrade --install fastapi ./helm-chart-fastapi --values=helm-chart-fastapi/values_dev.yaml --namespace dev
        
        
